# Site settings
title: Daily Herold
email: contact@johnpaulherold.com
description: "Developer by day, designer by night."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: thedailyherold 
github_username:  dailyherold

# Build settings
markdown: markdown
permalink: pretty
