# Site settings
title: DailyHerold
email: contact@johnpaulherold.com
description: "Developer by day, designer by night."
baseurl: ""
url: "http://dailyherold.net"
twitter_username: thedailyherold 
github_username:  dailyherold

# Build settings
markdown: kramdown
permalink: pretty
